twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/templates/partials': partials
        '%kernel.project_dir%/templates/main_page': main
        '%kernel.project_dir%/public/medias': medias

when@test:
    twig:
        strict_variables: true
