services:
  php:
    build:
      context: docker/environments/dev
      dockerfile: php/Dockerfile
    ports:
      - "9000:9000"
    entrypoint: ["sh", "/var/www/portfolio/docker/environments/dev/scripts/entrypoint.sh"]
  nginx:
    volumes:
      - ./docker/environments/dev/nginx:/etc/nginx/conf.d
