services:
  php:
    build:
      context: docker/environments/dev
      dockerfile: php/Dockerfile
      args:
          UID: ${UID}
          GID: ${GID}
    ports:
      - "9000:9000"
  nginx:
    volumes:
      - ./docker/environments/dev/nginx:/etc/nginx/conf.d
  node:
    working_dir: /var/www/portfolio
    entrypoint: [ "sh", "/var/www/portfolio/docker/environments/dev/node/scripts/entrypoint.sh" ]
    volumes:
        - .:/var/www/portfolio
    user: "${UID}:${GID}"

  postgresql:
    image: postgres:17.6-alpine3.22
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
