services:
  php:
    build:
      context: docker/environments/dev
      dockerfile: php/Dockerfile
      args:
          UID: ${UID}
          GID: ${GID}
    ports:
      - "9000:9000"
  nginx:
    volumes:
      - ./docker/environments/dev/nginx:/etc/nginx/conf.d
  node:
    working_dir: /var/www/portfolio
    entrypoint: [ "sh", "/var/www/portfolio/docker/environments/dev/node/scripts/entrypoint.sh" ]
    volumes:
        - .:/var/www/portfolio
    user: "${UID}:${GID}"
